python3 train.py \
    --model_name_or_path bert-base-uncased \
    --train_file data/wiki1m_for_simcse.txt \
    --output_dir experiments/unsup-corinfomax-bert-base-uncased-b50 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 256 \
    --learning_rate 1e-6 \
    --max_seq_length 32 \
    --evaluation_strategy steps \
    --metric_for_best_model stsb_spearman \
    --load_best_model_at_end \
    --eval_steps 150 \
    --save_steps 150 \
    --pooler_type cls \
    --mlp_only_train \
    --overwrite_output_dir \
    --temp 0.05 \
    --do_train \
    --do_proj \
    --augmentation_method dropout \
    --do_eval \
    --ssl_type corinfomax \
    --R_ini 1.00 \
    --la_R 0.01 \
    --la_mu 0.01 \
    --R_eps_weight 1e-8 \
    --proj_output_dim 8192-8192-8192 \
    --cov_loss_weight 1.5 \
    --sim_loss_weight 2000.0 \
    --cos_loss_weight 1.0 \
    --loss_elements cov-inv \
    --warmup_steps 1000 \
    --tensorboard_save_frequency 37 \
    --hidden_dropout_prob 0.1 \
    "$@"
